# Generated by Django 5.0.6 on 2024-05-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=100, unique=True)),
                ('ean', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
